### ISSUE TITLE
Exception being thrown at attempt to break at kernel32!CreateFileW and kernel32!CreateProcessW

### ISSUE THREAD

**Issue by mgeeky** [tehsyntx/loffice#2]
When trying to break at the `kernel32!CreateFileW` or `kernel32!CreateProcessW` in the lines:

```
        setup_breakpoint('kernel32', 'CreateProcessW', cb_createprocessw)
        setup_breakpoint('kernel32', 'CreateFileW', cb_createfilew)
```

there is an exception being thrown:

```
C:\Python27\lib\site-packages\winappdbg\event.py:1855: EventCallbackWarning: Event handler pre-callback <__main__.EventHandler object at 0x021A2850> raised an exception: Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\winappdbg\event.py", line 1850, in dispatch
    returnValue = self.__eventHandler(event)
  File "C:\Python27\lib\site-packages\winappdbg\event.py", line 1467, in __call__
    return method(event)
  File "loffice.py", line 168, in load_dll
    setup_breakpoint('kernel32', 'CreateProcessW', cb_createprocessw)
  File "loffice.py", line 150, in setup_breakpoint
    event.debug.break_at(pid, address, callback)
  File "C:\Python27\lib\site-packages\winappdbg\breakpoint.py", line 3927, in break_at
    bp = self.__set_break(pid, address, action, oneshot = False)
  File "C:\Python27\lib\site-packages\winappdbg\breakpoint.py", line 3767, in __set_break
    self.enable_code_breakpoint(pid, address)
  File "C:\Python27\lib\site-packages\winappdbg\breakpoint.py", line 2660, in enable_code_breakpoint
    bp.enable(p, None)        # XXX HACK thread is not used
  File "C:\Python27\lib\site-packages\winappdbg\breakpoint.py", line 612, in enable
    self.__set_bp(aProcess)
  File "C:\Python27\lib\site-packages\winappdbg\breakpoint.py", line 580, in __set_bp
    self.__previousValue = aProcess.read(address, len(self.bpInstruction))
  File "C:\Python27\lib\site-packages\winappdbg\process.py", line 1596, in read
    raise ctypes.WinError(win32.ERROR_INVALID_ADDRESS)
WindowsError: [Error 487] Attempt to access invalid address.

  warnings.warn(msg, EventCallbackWarning)
```

At the instruction:
`event.debug.break_at(pid, address, callback)`

The address that is returned by module.resolve(...) was different that the one that was returned by `x kernel32!CreateFileW` command inside of Windbg. The problem may be with the `winappdbg.module.resolve(...)` function itself.

Anyway, right now the script may be inoperable (as tested under the Win7 x86 and Office15 / Excel) when dealing with `CreateFile`and `CreateProcess`related events.

Tried to approach this with the following attempt:

```
class EventHandler(EventHandler):

    lazy_break_list = []

    def load_dll(self, event):

        module = event.get_module()
        pid = event.get_pid()

        self.evaluate_lazy_break_list(pid, event)

        def setup_breakpoint(modulename, function, callback):
            if module.match_name(modulename + '.dll'):
                address = module.resolve(function)
                try:
                    if address:
                        print address
                        event.debug.break_at(pid, address, callback)
                    else:
                        logger.warning("Couldn't resolve or address not belong to module: %s!%s" % (modulename, function))
                except:
                    self.lazy_break_list.append((module.get_name(), function, callback))
                    logger.error('Could not break at: %s!%s. Adding to lazy break list...' % (modulename, function))

        setup_breakpoint('kernel32', 'CreateProcessW', cb_createprocessw)
        setup_breakpoint('kernel32', 'CreateFileW', cb_createfilew)
        setup_breakpoint('wininet', 'InternetCrackUrlW', cb_crackurl)
        setup_breakpoint('winhttp', 'WinHttpCrackUrl', cb_crackurl)
        setup_breakpoint('ole32', 'ObjectStublessClient20', cb_stubclient20)

        # Development in progress...
        #setup_breakpoint('advapi32', 'RegSetValueExW', cb_regsetvalueexw)

    def evaluate_lazy_break_list(self, pid, event):
        process = event.get_process()
        for (modulename, function, callback) in self.lazy_break_list:
            try:
                module = process.get_module_by_name(modulename)
                if module:
                    address = module.resolve(function)
                    if address:
                        print address
                        event.debug.break_at(pid, address, callback)    
                        logger.debug('Succeed at setting breakpoint on %s!%s in the lazy break approach.')
                    else: raise Exception
                else: raise Exception
            except:
                pass
```

Specifically by using the `evaluate_lazy_break_list` snippet, but acquiring method's address in the runtime have not worked as well (also the `GetModuleHandleW` + `GetProcAddress`approach didn't get me anywhere).

Currently we will have the following error messages remind about this issue:

```
[ERROR] Could not break at: kernel32!CreateProcessW.
[ERROR] Could not break at: kernel32!CreateFileW.
```

Anyway, this issue is worth further investigation, although I do not have enough spare time at the moment. Will back to this issue soon. :)

**Comment by tehsyntx** [comment]
I presume that this was one of the reasons to add try...except in the last commit. I've been running the loffice code (not the above snippet) on a couple of different machines without having any problems, have you tried running it on a different machine?

**Comment by mgeeky** [comment]
Will investigate this in couple of days, since I would like to get it closed :)

**Comment by tehsyntx** [comment]
closing, re-open if problem still exists.
