### ISSUE TITLE
Error Running on Windows 8.1 32 bit platform

### ISSUE THREAD

**Issue by wizkidnc** [tehsyntx/loffice#5]
getting the following error running on windows 8.1
Traceback (most recent call last):
  File "C:\Tools\loffice-master\loffice.py", line 325, in <module>
    debug.execv(office_invoke)
  File "C:\Python27\lib\site-packages\winappdbg\debug.py", line 347, in execv
    return self.execl(lpCmdLine, *_kwargs)
  File "C:\Python27\lib\site-packages\winappdbg\debug.py", line 490, in execl
    aProcess = self.system.start_process(lpCmdLine, *_kwargs)
  File "C:\Python27\lib\site-packages\winappdbg\process.py", line 4253, in start_process
    lpStartupInfo   = lpStartupInfo)
  File "C:\Python27\lib\site-packages\winappdbg\win32\defines.py", line 253, in **call**
    return fn(_argv, *_argd)
  File "C:\Python27\lib\site-packages\winappdbg\win32\kernel32.py", line 3854, in CreateProcessA
    _CreateProcessA(lpApplicationName, lpCommandLine, lpProcessAttributes, lpThreadAttributes, bool(bInheritHandles), dwCreationFlags, lpEnvironment, lpC
urrentDirectory, byref(lpStartupInfo), byref(lpProcessInformation))
  File "C:\Python27\lib\site-packages\winappdbg\win32\defines.py", line 130, in RaiseIfZero
    raise ctypes.WinError()
WindowsError: [Error 2] The system cannot find the file specified.

Is this compatible with this version of windows?

**Comment by tehsyntx** [comment]
Have you specified the correct path to Office? Either you can do it in the code on line 30 or use the -p flag.

**Comment by wizkidnc** [comment]
Thanks that did it! This tool is awesome!
In case anyone is having issues running on Windows 8.1 just had to change the default path to \Microsoft Office\**root**\Office16

**Comment by tehsyntx** [comment]
Great! :)

Just locate for example word.exe and you're good to go. I'll make sure to fix a more informative error message for this other than a cryptic traceback.
