### ISSUE TITLE
Can't get it to successfully run

### ISSUE THREAD

**Issue by ottoscav** [tehsyntx/loffice#8]
This is probably some dumb user error that I'm screwing up myself....but I cannot seem to get it to work. 

Here is the error I'm getting:

C:\Users\User\Desktop\loffice-master>python loffice.py word proc irs_scanned__05
6781.doc

```
    Lazy Office Analyzer - Analyze documents with WinDbg
```

Traceback (most recent call last):
  File "loffice.py", line 325, in <module>
    debug.execv(office_invoke)
  File "C:\Python27\lib\site-packages\winappdbg\debug.py", line 347, in execv
    return self.execl(lpCmdLine, *_kwargs)
  File "C:\Python27\lib\site-packages\winappdbg\debug.py", line 490, in execl
    aProcess = self.system.start_process(lpCmdLine, *_kwargs)
  File "C:\Python27\lib\site-packages\winappdbg\process.py", line 4253, in start
_process
    lpStartupInfo   = lpStartupInfo)
  File "C:\Python27\lib\site-packages\winappdbg\win32\defines.py", line 253, in
__call__
    return fn(_argv, *_argd)
  File "C:\Python27\lib\site-packages\winappdbg\win32\kernel32.py", line 3854, i
n CreateProcessA
    _CreateProcessA(lpApplicationName, lpCommandLine, lpProcessAttributes, lpThr
eadAttributes, bool(bInheritHandles), dwCreationFlags, lpEnvironment, lpCurrentD
irectory, byref(lpStartupInfo), byref(lpProcessInformation))
  File "C:\Python27\lib\site-packages\winappdbg\win32\defines.py", line 130, in
RaiseIfZero
    raise ctypes.WinError()
WindowsError: [Error 2] The system cannot find the file specified.

C:\Users\User\Desktop\loffice-master>

Ideas? The file is in the same folder as the python script. 

Thanks!

**Comment by tehsyntx** [comment]
Most likely invalid path to Office, verify that DEFAULT_OFFICE_PATH points to your installation, usual mistake is the folder name for example "Office16" instead of "Office14" depending on version. Let me know if that worked or not.

I'll make this error more "clear" in the upcoming version (hopefully) this weekend.

**Comment by tehsyntx** [comment]
Closing due to no feedback.
